version: "3.8"
services:
  movies:
    image: ghaffarbajwa9/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: ghaffarbajwa9/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  tickets:
    image: ghaffarbajwa9/paytickets:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
